// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/spire/spire_service.proto

#include "proto/spire/spire_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_proto_2fspire_2fspire_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fspire_2fspire_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fspire_2fspire_5fservice_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fspire_2fspire_5fservice_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_proto_2fspire_2fspire_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037proto/spire/spire_service.proto\032\027proto"
  "/spire/spire.proto\032\036proto/utils/data_exa"
  "mple.proto\032\033proto/utils/databatch.proto2"
  "\345\006\n\014SpireService\022@\n\rSpireGetState\022\025.Spir"
  "eGetStateRequest\032\026.SpireGetStateResponse"
  "\"\000\022C\n\016SpireGetConfig\022\026.SpireGetConfigReq"
  "uest\032\027.SpireGetConfigResponse\"\000\022C\n\016Spire"
  "SetConfig\022\026.SpireSetConfigRequest\032\027.Spir"
  "eSetConfigResponse\"\000\022@\n\rSpireMaybeJIT\022\025."
  "SpireMaybeJITRequest\032\026.SpireMaybeJITResp"
  "onse\"\000\022I\n\020SpireStopServing\022\030.SpireStopSe"
  "rvingRequest\032\031.SpireStopServingResponse\""
  "\000\022@\n\rSpireEmbedTag\022\025.SpireEmbedTagReques"
  "t\032\026.SpireEmbedTagResponse\"\000\022I\n\020SpireSave"
  "dOutput\022\030.SpireSavedOutputRequest\032\031.Spir"
  "eSavedOutputResponse\"\000\022^\n\027SpireFaceDetec"
  "tEmbedTag\022\037.SpireFaceDetectEmbedTagReque"
  "st\032 .SpireFaceDetectEmbedTagResponse\"\000\022R"
  "\n\023SpireDetectEmbedTag\022\033.SpireDetectEmbed"
  "TagRequest\032\034.SpireDetectEmbedTagResponse"
  "\"\000\022:\n\013SpireDetect\022\023.SpireDetectRequest\032\024"
  ".SpireDetectResponse\"\000\022(\n\nSpireTrack\022\014.D"
  "ataExample\032\n.DataBatch\"\000\022U\n\024SpireInstanc"
  "eSegment\022\034.SpireInstanceSegmentRequest\032\035"
  ".SpireInstanceSegmentResponse\"\000B\007Z\005spire"
  "b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fspire_2fspire_5fservice_2eproto_deps[3] = {
  &::descriptor_table_proto_2fspire_2fspire_2eproto,
  &::descriptor_table_proto_2futils_2fdata_5fexample_2eproto,
  &::descriptor_table_proto_2futils_2fdatabatch_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fspire_2fspire_5fservice_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fspire_2fspire_5fservice_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fspire_2fspire_5fservice_2eproto = {
  false, false, descriptor_table_protodef_proto_2fspire_2fspire_5fservice_2eproto, "proto/spire/spire_service.proto", 1008,
  &descriptor_table_proto_2fspire_2fspire_5fservice_2eproto_once, descriptor_table_proto_2fspire_2fspire_5fservice_2eproto_sccs, descriptor_table_proto_2fspire_2fspire_5fservice_2eproto_deps, 0, 3,
  schemas, file_default_instances, TableStruct_proto_2fspire_2fspire_5fservice_2eproto::offsets,
  file_level_metadata_proto_2fspire_2fspire_5fservice_2eproto, 0, file_level_enum_descriptors_proto_2fspire_2fspire_5fservice_2eproto, file_level_service_descriptors_proto_2fspire_2fspire_5fservice_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fspire_2fspire_5fservice_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fspire_2fspire_5fservice_2eproto)), true);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
