// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/knowledge_graph/kg_py_service.proto

#include "proto/knowledge_graph/kg_py_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_proto_2futils_2fdata_5fexample_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<18> scc_info_DataExample_proto_2futils_2fdata_5fexample_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2futils_2frequest_5fmeta_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RequestMeta_proto_2futils_2frequest_5fmeta_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2futils_2frequest_5fmeta_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ResponseStatus_proto_2futils_2frequest_5fmeta_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fclarifai_2fapi_2fresources_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Concept_proto_2fclarifai_2fapi_2fresources_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ConceptEmbeddingDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ConceptMap_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_CustomerDataDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto;
namespace clarifai {
namespace api {
class ConceptMapDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ConceptMap> _instance;
} _ConceptMap_default_instance_;
class ConceptEmbeddingDumpDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ConceptEmbeddingDump> _instance;
} _ConceptEmbeddingDump_default_instance_;
class CustomerDataDumpDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CustomerDataDump> _instance;
} _CustomerDataDump_default_instance_;
class PostKnowledgeGraphMatchRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PostKnowledgeGraphMatchRequest> _instance;
} _PostKnowledgeGraphMatchRequest_default_instance_;
class PostKnowledgeGraphMatchResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PostKnowledgeGraphMatchResponse> _instance;
} _PostKnowledgeGraphMatchResponse_default_instance_;
}  // namespace api
}  // namespace clarifai
static void InitDefaultsscc_info_ConceptEmbeddingDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::clarifai::api::_ConceptEmbeddingDump_default_instance_;
    new (ptr) ::clarifai::api::ConceptEmbeddingDump();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::clarifai::api::ConceptEmbeddingDump::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ConceptEmbeddingDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ConceptEmbeddingDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto}, {
      &scc_info_DataExample_proto_2futils_2fdata_5fexample_2eproto.base,}};

static void InitDefaultsscc_info_ConceptMap_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::clarifai::api::_ConceptMap_default_instance_;
    new (ptr) ::clarifai::api::ConceptMap();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::clarifai::api::ConceptMap::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ConceptMap_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ConceptMap_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto}, {
      &scc_info_Concept_proto_2fclarifai_2fapi_2fresources_2eproto.base,}};

static void InitDefaultsscc_info_CustomerDataDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::clarifai::api::_CustomerDataDump_default_instance_;
    new (ptr) ::clarifai::api::CustomerDataDump();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::clarifai::api::CustomerDataDump::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_CustomerDataDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_CustomerDataDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto}, {
      &scc_info_DataExample_proto_2futils_2fdata_5fexample_2eproto.base,}};

static void InitDefaultsscc_info_PostKnowledgeGraphMatchRequest_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::clarifai::api::_PostKnowledgeGraphMatchRequest_default_instance_;
    new (ptr) ::clarifai::api::PostKnowledgeGraphMatchRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::clarifai::api::PostKnowledgeGraphMatchRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_PostKnowledgeGraphMatchRequest_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_PostKnowledgeGraphMatchRequest_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto}, {
      &scc_info_RequestMeta_proto_2futils_2frequest_5fmeta_2eproto.base,
      &scc_info_CustomerDataDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base,
      &scc_info_ConceptEmbeddingDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base,}};

static void InitDefaultsscc_info_PostKnowledgeGraphMatchResponse_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::clarifai::api::_PostKnowledgeGraphMatchResponse_default_instance_;
    new (ptr) ::clarifai::api::PostKnowledgeGraphMatchResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::clarifai::api::PostKnowledgeGraphMatchResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_PostKnowledgeGraphMatchResponse_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_PostKnowledgeGraphMatchResponse_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto}, {
      &scc_info_ResponseStatus_proto_2futils_2frequest_5fmeta_2eproto.base,
      &scc_info_ConceptMap_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::ConceptMap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::ConceptMap, customer_concept_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::ConceptMap, golden_concept_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::ConceptEmbeddingDump, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::ConceptEmbeddingDump, location_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::ConceptEmbeddingDump, example_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::CustomerDataDump, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::CustomerDataDump, locaiton_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::CustomerDataDump, example_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchRequest, meta_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchRequest, children_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchRequest, siblings_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchRequest, max_depth_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchRequest, max_width_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchRequest, customer_data_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchRequest, shareable_concept_embeddings_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchResponse, status_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::PostKnowledgeGraphMatchResponse, concept_map_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::clarifai::api::ConceptMap)},
  { 7, -1, sizeof(::clarifai::api::ConceptEmbeddingDump)},
  { 14, -1, sizeof(::clarifai::api::CustomerDataDump)},
  { 21, -1, sizeof(::clarifai::api::PostKnowledgeGraphMatchRequest)},
  { 33, -1, sizeof(::clarifai::api::PostKnowledgeGraphMatchResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::clarifai::api::_ConceptMap_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::clarifai::api::_ConceptEmbeddingDump_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::clarifai::api::_CustomerDataDump_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::clarifai::api::_PostKnowledgeGraphMatchRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::clarifai::api::_PostKnowledgeGraphMatchResponse_default_instance_),
};

const char descriptor_table_protodef_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n)proto/knowledge_graph/kg_py_service.pr"
  "oto\022\014clarifai.api\032\"proto/clarifai/api/re"
  "sources.proto\032\036proto/utils/request_meta."
  "proto\032\036proto/utils/data_example.proto\"l\n"
  "\nConceptMap\022/\n\020customer_concept\030\001 \001(\0132\025."
  "clarifai.api.Concept\022-\n\016golden_concept\030\002"
  " \003(\0132\025.clarifai.api.Concept\"G\n\024ConceptEm"
  "beddingDump\022\020\n\010location\030\001 \001(\t\022\035\n\007example"
  "\030\002 \003(\0132\014.DataExample\"C\n\020CustomerDataDump"
  "\022\020\n\010locaiton\030\001 \001(\t\022\035\n\007example\030\002 \003(\0132\014.Da"
  "taExample\"\207\002\n\036PostKnowledgeGraphMatchReq"
  "uest\022\032\n\004meta\030\001 \001(\0132\014.RequestMeta\022\020\n\010chil"
  "dren\030\002 \001(\010\022\020\n\010siblings\030\003 \001(\010\022\021\n\tmax_dept"
  "h\030\004 \001(\005\022\021\n\tmax_width\030\005 \001(\005\0225\n\rcustomer_d"
  "ata\030\006 \001(\0132\036.clarifai.api.CustomerDataDum"
  "p\022H\n\034shareable_concept_embeddings\030\007 \003(\0132"
  "\".clarifai.api.ConceptEmbeddingDump\"q\n\037P"
  "ostKnowledgeGraphMatchResponse\022\037\n\006status"
  "\030\001 \001(\0132\017.ResponseStatus\022-\n\013concept_map\030\002"
  " \003(\0132\030.clarifai.api.ConceptMapB\014Z\003api\242\002\004"
  "CAIPb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto_deps[3] = {
  &::descriptor_table_proto_2fclarifai_2fapi_2fresources_2eproto,
  &::descriptor_table_proto_2futils_2fdata_5fexample_2eproto,
  &::descriptor_table_proto_2futils_2frequest_5fmeta_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto_sccs[5] = {
  &scc_info_ConceptEmbeddingDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base,
  &scc_info_ConceptMap_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base,
  &scc_info_CustomerDataDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base,
  &scc_info_PostKnowledgeGraphMatchRequest_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base,
  &scc_info_PostKnowledgeGraphMatchResponse_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto = {
  false, false, descriptor_table_protodef_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto, "proto/knowledge_graph/kg_py_service.proto", 812,
  &descriptor_table_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto_once, descriptor_table_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto_sccs, descriptor_table_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto_deps, 5, 3,
  schemas, file_default_instances, TableStruct_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto::offsets,
  file_level_metadata_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto, 5, file_level_enum_descriptors_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto, file_level_service_descriptors_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto)), true);
namespace clarifai {
namespace api {

// ===================================================================

void ConceptMap::InitAsDefaultInstance() {
  ::clarifai::api::_ConceptMap_default_instance_._instance.get_mutable()->customer_concept_ = const_cast< ::clarifai::api::Concept*>(
      ::clarifai::api::Concept::internal_default_instance());
}
class ConceptMap::_Internal {
 public:
  static const ::clarifai::api::Concept& customer_concept(const ConceptMap* msg);
};

const ::clarifai::api::Concept&
ConceptMap::_Internal::customer_concept(const ConceptMap* msg) {
  return *msg->customer_concept_;
}
void ConceptMap::clear_customer_concept() {
  if (GetArena() == nullptr && customer_concept_ != nullptr) {
    delete customer_concept_;
  }
  customer_concept_ = nullptr;
}
void ConceptMap::clear_golden_concept() {
  golden_concept_.Clear();
}
ConceptMap::ConceptMap(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  golden_concept_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.ConceptMap)
}
ConceptMap::ConceptMap(const ConceptMap& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      golden_concept_(from.golden_concept_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_customer_concept()) {
    customer_concept_ = new ::clarifai::api::Concept(*from.customer_concept_);
  } else {
    customer_concept_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:clarifai.api.ConceptMap)
}

void ConceptMap::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ConceptMap_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  customer_concept_ = nullptr;
}

ConceptMap::~ConceptMap() {
  // @@protoc_insertion_point(destructor:clarifai.api.ConceptMap)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ConceptMap::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete customer_concept_;
}

void ConceptMap::ArenaDtor(void* object) {
  ConceptMap* _this = reinterpret_cast< ConceptMap* >(object);
  (void)_this;
}
void ConceptMap::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ConceptMap::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConceptMap& ConceptMap::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ConceptMap_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ConceptMap::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.ConceptMap)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  golden_concept_.Clear();
  if (GetArena() == nullptr && customer_concept_ != nullptr) {
    delete customer_concept_;
  }
  customer_concept_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ConceptMap::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .clarifai.api.Concept customer_concept = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_customer_concept(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .clarifai.api.Concept golden_concept = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_golden_concept(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ConceptMap::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.ConceptMap)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .clarifai.api.Concept customer_concept = 1;
  if (this->has_customer_concept()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::customer_concept(this), target, stream);
  }

  // repeated .clarifai.api.Concept golden_concept = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_golden_concept_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_golden_concept(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.ConceptMap)
  return target;
}

size_t ConceptMap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.ConceptMap)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .clarifai.api.Concept golden_concept = 2;
  total_size += 1UL * this->_internal_golden_concept_size();
  for (const auto& msg : this->golden_concept_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .clarifai.api.Concept customer_concept = 1;
  if (this->has_customer_concept()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *customer_concept_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConceptMap::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:clarifai.api.ConceptMap)
  GOOGLE_DCHECK_NE(&from, this);
  const ConceptMap* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ConceptMap>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:clarifai.api.ConceptMap)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:clarifai.api.ConceptMap)
    MergeFrom(*source);
  }
}

void ConceptMap::MergeFrom(const ConceptMap& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.ConceptMap)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  golden_concept_.MergeFrom(from.golden_concept_);
  if (from.has_customer_concept()) {
    _internal_mutable_customer_concept()->::clarifai::api::Concept::MergeFrom(from._internal_customer_concept());
  }
}

void ConceptMap::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:clarifai.api.ConceptMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConceptMap::CopyFrom(const ConceptMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.ConceptMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConceptMap::IsInitialized() const {
  return true;
}

void ConceptMap::InternalSwap(ConceptMap* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  golden_concept_.InternalSwap(&other->golden_concept_);
  swap(customer_concept_, other->customer_concept_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ConceptMap::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ConceptEmbeddingDump::InitAsDefaultInstance() {
}
class ConceptEmbeddingDump::_Internal {
 public:
};

void ConceptEmbeddingDump::clear_example() {
  example_.Clear();
}
ConceptEmbeddingDump::ConceptEmbeddingDump(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  example_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.ConceptEmbeddingDump)
}
ConceptEmbeddingDump::ConceptEmbeddingDump(const ConceptEmbeddingDump& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      example_(from.example_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  location_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_location().empty()) {
    location_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_location(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:clarifai.api.ConceptEmbeddingDump)
}

void ConceptEmbeddingDump::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ConceptEmbeddingDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  location_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

ConceptEmbeddingDump::~ConceptEmbeddingDump() {
  // @@protoc_insertion_point(destructor:clarifai.api.ConceptEmbeddingDump)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ConceptEmbeddingDump::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  location_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ConceptEmbeddingDump::ArenaDtor(void* object) {
  ConceptEmbeddingDump* _this = reinterpret_cast< ConceptEmbeddingDump* >(object);
  (void)_this;
}
void ConceptEmbeddingDump::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ConceptEmbeddingDump::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConceptEmbeddingDump& ConceptEmbeddingDump::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ConceptEmbeddingDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ConceptEmbeddingDump::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.ConceptEmbeddingDump)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  example_.Clear();
  location_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ConceptEmbeddingDump::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string location = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_location();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "clarifai.api.ConceptEmbeddingDump.location"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .DataExample example = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_example(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ConceptEmbeddingDump::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.ConceptEmbeddingDump)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string location = 1;
  if (this->location().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_location().data(), static_cast<int>(this->_internal_location().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.ConceptEmbeddingDump.location");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_location(), target);
  }

  // repeated .DataExample example = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_example_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_example(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.ConceptEmbeddingDump)
  return target;
}

size_t ConceptEmbeddingDump::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.ConceptEmbeddingDump)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .DataExample example = 2;
  total_size += 1UL * this->_internal_example_size();
  for (const auto& msg : this->example_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string location = 1;
  if (this->location().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_location());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConceptEmbeddingDump::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:clarifai.api.ConceptEmbeddingDump)
  GOOGLE_DCHECK_NE(&from, this);
  const ConceptEmbeddingDump* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ConceptEmbeddingDump>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:clarifai.api.ConceptEmbeddingDump)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:clarifai.api.ConceptEmbeddingDump)
    MergeFrom(*source);
  }
}

void ConceptEmbeddingDump::MergeFrom(const ConceptEmbeddingDump& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.ConceptEmbeddingDump)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  example_.MergeFrom(from.example_);
  if (from.location().size() > 0) {
    _internal_set_location(from._internal_location());
  }
}

void ConceptEmbeddingDump::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:clarifai.api.ConceptEmbeddingDump)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConceptEmbeddingDump::CopyFrom(const ConceptEmbeddingDump& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.ConceptEmbeddingDump)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConceptEmbeddingDump::IsInitialized() const {
  return true;
}

void ConceptEmbeddingDump::InternalSwap(ConceptEmbeddingDump* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  example_.InternalSwap(&other->example_);
  location_.Swap(&other->location_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata ConceptEmbeddingDump::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void CustomerDataDump::InitAsDefaultInstance() {
}
class CustomerDataDump::_Internal {
 public:
};

void CustomerDataDump::clear_example() {
  example_.Clear();
}
CustomerDataDump::CustomerDataDump(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  example_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.CustomerDataDump)
}
CustomerDataDump::CustomerDataDump(const CustomerDataDump& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      example_(from.example_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  locaiton_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_locaiton().empty()) {
    locaiton_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_locaiton(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:clarifai.api.CustomerDataDump)
}

void CustomerDataDump::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CustomerDataDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  locaiton_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

CustomerDataDump::~CustomerDataDump() {
  // @@protoc_insertion_point(destructor:clarifai.api.CustomerDataDump)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CustomerDataDump::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  locaiton_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void CustomerDataDump::ArenaDtor(void* object) {
  CustomerDataDump* _this = reinterpret_cast< CustomerDataDump* >(object);
  (void)_this;
}
void CustomerDataDump::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CustomerDataDump::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CustomerDataDump& CustomerDataDump::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CustomerDataDump_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  return *internal_default_instance();
}


void CustomerDataDump::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.CustomerDataDump)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  example_.Clear();
  locaiton_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CustomerDataDump::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string locaiton = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_locaiton();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "clarifai.api.CustomerDataDump.locaiton"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .DataExample example = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_example(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CustomerDataDump::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.CustomerDataDump)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string locaiton = 1;
  if (this->locaiton().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_locaiton().data(), static_cast<int>(this->_internal_locaiton().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.CustomerDataDump.locaiton");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_locaiton(), target);
  }

  // repeated .DataExample example = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_example_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_example(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.CustomerDataDump)
  return target;
}

size_t CustomerDataDump::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.CustomerDataDump)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .DataExample example = 2;
  total_size += 1UL * this->_internal_example_size();
  for (const auto& msg : this->example_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string locaiton = 1;
  if (this->locaiton().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_locaiton());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CustomerDataDump::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:clarifai.api.CustomerDataDump)
  GOOGLE_DCHECK_NE(&from, this);
  const CustomerDataDump* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CustomerDataDump>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:clarifai.api.CustomerDataDump)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:clarifai.api.CustomerDataDump)
    MergeFrom(*source);
  }
}

void CustomerDataDump::MergeFrom(const CustomerDataDump& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.CustomerDataDump)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  example_.MergeFrom(from.example_);
  if (from.locaiton().size() > 0) {
    _internal_set_locaiton(from._internal_locaiton());
  }
}

void CustomerDataDump::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:clarifai.api.CustomerDataDump)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CustomerDataDump::CopyFrom(const CustomerDataDump& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.CustomerDataDump)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CustomerDataDump::IsInitialized() const {
  return true;
}

void CustomerDataDump::InternalSwap(CustomerDataDump* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  example_.InternalSwap(&other->example_);
  locaiton_.Swap(&other->locaiton_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata CustomerDataDump::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PostKnowledgeGraphMatchRequest::InitAsDefaultInstance() {
  ::clarifai::api::_PostKnowledgeGraphMatchRequest_default_instance_._instance.get_mutable()->meta_ = const_cast< ::RequestMeta*>(
      ::RequestMeta::internal_default_instance());
  ::clarifai::api::_PostKnowledgeGraphMatchRequest_default_instance_._instance.get_mutable()->customer_data_ = const_cast< ::clarifai::api::CustomerDataDump*>(
      ::clarifai::api::CustomerDataDump::internal_default_instance());
}
class PostKnowledgeGraphMatchRequest::_Internal {
 public:
  static const ::RequestMeta& meta(const PostKnowledgeGraphMatchRequest* msg);
  static const ::clarifai::api::CustomerDataDump& customer_data(const PostKnowledgeGraphMatchRequest* msg);
};

const ::RequestMeta&
PostKnowledgeGraphMatchRequest::_Internal::meta(const PostKnowledgeGraphMatchRequest* msg) {
  return *msg->meta_;
}
const ::clarifai::api::CustomerDataDump&
PostKnowledgeGraphMatchRequest::_Internal::customer_data(const PostKnowledgeGraphMatchRequest* msg) {
  return *msg->customer_data_;
}
void PostKnowledgeGraphMatchRequest::clear_meta() {
  if (GetArena() == nullptr && meta_ != nullptr) {
    delete meta_;
  }
  meta_ = nullptr;
}
PostKnowledgeGraphMatchRequest::PostKnowledgeGraphMatchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  shareable_concept_embeddings_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.PostKnowledgeGraphMatchRequest)
}
PostKnowledgeGraphMatchRequest::PostKnowledgeGraphMatchRequest(const PostKnowledgeGraphMatchRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      shareable_concept_embeddings_(from.shareable_concept_embeddings_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_meta()) {
    meta_ = new ::RequestMeta(*from.meta_);
  } else {
    meta_ = nullptr;
  }
  if (from._internal_has_customer_data()) {
    customer_data_ = new ::clarifai::api::CustomerDataDump(*from.customer_data_);
  } else {
    customer_data_ = nullptr;
  }
  ::memcpy(&children_, &from.children_,
    static_cast<size_t>(reinterpret_cast<char*>(&max_width_) -
    reinterpret_cast<char*>(&children_)) + sizeof(max_width_));
  // @@protoc_insertion_point(copy_constructor:clarifai.api.PostKnowledgeGraphMatchRequest)
}

void PostKnowledgeGraphMatchRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PostKnowledgeGraphMatchRequest_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  ::memset(&meta_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_width_) -
      reinterpret_cast<char*>(&meta_)) + sizeof(max_width_));
}

PostKnowledgeGraphMatchRequest::~PostKnowledgeGraphMatchRequest() {
  // @@protoc_insertion_point(destructor:clarifai.api.PostKnowledgeGraphMatchRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PostKnowledgeGraphMatchRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete meta_;
  if (this != internal_default_instance()) delete customer_data_;
}

void PostKnowledgeGraphMatchRequest::ArenaDtor(void* object) {
  PostKnowledgeGraphMatchRequest* _this = reinterpret_cast< PostKnowledgeGraphMatchRequest* >(object);
  (void)_this;
}
void PostKnowledgeGraphMatchRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PostKnowledgeGraphMatchRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PostKnowledgeGraphMatchRequest& PostKnowledgeGraphMatchRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PostKnowledgeGraphMatchRequest_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  return *internal_default_instance();
}


void PostKnowledgeGraphMatchRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.PostKnowledgeGraphMatchRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  shareable_concept_embeddings_.Clear();
  if (GetArena() == nullptr && meta_ != nullptr) {
    delete meta_;
  }
  meta_ = nullptr;
  if (GetArena() == nullptr && customer_data_ != nullptr) {
    delete customer_data_;
  }
  customer_data_ = nullptr;
  ::memset(&children_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&max_width_) -
      reinterpret_cast<char*>(&children_)) + sizeof(max_width_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PostKnowledgeGraphMatchRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .RequestMeta meta = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_meta(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool children = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          children_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool siblings = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          siblings_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 max_depth = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          max_depth_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 max_width = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          max_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .clarifai.api.CustomerDataDump customer_data = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_customer_data(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .clarifai.api.ConceptEmbeddingDump shareable_concept_embeddings = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_shareable_concept_embeddings(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PostKnowledgeGraphMatchRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.PostKnowledgeGraphMatchRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .RequestMeta meta = 1;
  if (this->has_meta()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::meta(this), target, stream);
  }

  // bool children = 2;
  if (this->children() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_children(), target);
  }

  // bool siblings = 3;
  if (this->siblings() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_siblings(), target);
  }

  // int32 max_depth = 4;
  if (this->max_depth() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_max_depth(), target);
  }

  // int32 max_width = 5;
  if (this->max_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_max_width(), target);
  }

  // .clarifai.api.CustomerDataDump customer_data = 6;
  if (this->has_customer_data()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::customer_data(this), target, stream);
  }

  // repeated .clarifai.api.ConceptEmbeddingDump shareable_concept_embeddings = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_shareable_concept_embeddings_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, this->_internal_shareable_concept_embeddings(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.PostKnowledgeGraphMatchRequest)
  return target;
}

size_t PostKnowledgeGraphMatchRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.PostKnowledgeGraphMatchRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .clarifai.api.ConceptEmbeddingDump shareable_concept_embeddings = 7;
  total_size += 1UL * this->_internal_shareable_concept_embeddings_size();
  for (const auto& msg : this->shareable_concept_embeddings_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .RequestMeta meta = 1;
  if (this->has_meta()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *meta_);
  }

  // .clarifai.api.CustomerDataDump customer_data = 6;
  if (this->has_customer_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *customer_data_);
  }

  // bool children = 2;
  if (this->children() != 0) {
    total_size += 1 + 1;
  }

  // bool siblings = 3;
  if (this->siblings() != 0) {
    total_size += 1 + 1;
  }

  // int32 max_depth = 4;
  if (this->max_depth() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_max_depth());
  }

  // int32 max_width = 5;
  if (this->max_width() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_max_width());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PostKnowledgeGraphMatchRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:clarifai.api.PostKnowledgeGraphMatchRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const PostKnowledgeGraphMatchRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PostKnowledgeGraphMatchRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:clarifai.api.PostKnowledgeGraphMatchRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:clarifai.api.PostKnowledgeGraphMatchRequest)
    MergeFrom(*source);
  }
}

void PostKnowledgeGraphMatchRequest::MergeFrom(const PostKnowledgeGraphMatchRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.PostKnowledgeGraphMatchRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  shareable_concept_embeddings_.MergeFrom(from.shareable_concept_embeddings_);
  if (from.has_meta()) {
    _internal_mutable_meta()->::RequestMeta::MergeFrom(from._internal_meta());
  }
  if (from.has_customer_data()) {
    _internal_mutable_customer_data()->::clarifai::api::CustomerDataDump::MergeFrom(from._internal_customer_data());
  }
  if (from.children() != 0) {
    _internal_set_children(from._internal_children());
  }
  if (from.siblings() != 0) {
    _internal_set_siblings(from._internal_siblings());
  }
  if (from.max_depth() != 0) {
    _internal_set_max_depth(from._internal_max_depth());
  }
  if (from.max_width() != 0) {
    _internal_set_max_width(from._internal_max_width());
  }
}

void PostKnowledgeGraphMatchRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:clarifai.api.PostKnowledgeGraphMatchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PostKnowledgeGraphMatchRequest::CopyFrom(const PostKnowledgeGraphMatchRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.PostKnowledgeGraphMatchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PostKnowledgeGraphMatchRequest::IsInitialized() const {
  return true;
}

void PostKnowledgeGraphMatchRequest::InternalSwap(PostKnowledgeGraphMatchRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  shareable_concept_embeddings_.InternalSwap(&other->shareable_concept_embeddings_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PostKnowledgeGraphMatchRequest, max_width_)
      + sizeof(PostKnowledgeGraphMatchRequest::max_width_)
      - PROTOBUF_FIELD_OFFSET(PostKnowledgeGraphMatchRequest, meta_)>(
          reinterpret_cast<char*>(&meta_),
          reinterpret_cast<char*>(&other->meta_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PostKnowledgeGraphMatchRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PostKnowledgeGraphMatchResponse::InitAsDefaultInstance() {
  ::clarifai::api::_PostKnowledgeGraphMatchResponse_default_instance_._instance.get_mutable()->status_ = const_cast< ::ResponseStatus*>(
      ::ResponseStatus::internal_default_instance());
}
class PostKnowledgeGraphMatchResponse::_Internal {
 public:
  static const ::ResponseStatus& status(const PostKnowledgeGraphMatchResponse* msg);
};

const ::ResponseStatus&
PostKnowledgeGraphMatchResponse::_Internal::status(const PostKnowledgeGraphMatchResponse* msg) {
  return *msg->status_;
}
void PostKnowledgeGraphMatchResponse::clear_status() {
  if (GetArena() == nullptr && status_ != nullptr) {
    delete status_;
  }
  status_ = nullptr;
}
PostKnowledgeGraphMatchResponse::PostKnowledgeGraphMatchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  concept_map_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.PostKnowledgeGraphMatchResponse)
}
PostKnowledgeGraphMatchResponse::PostKnowledgeGraphMatchResponse(const PostKnowledgeGraphMatchResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      concept_map_(from.concept_map_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_status()) {
    status_ = new ::ResponseStatus(*from.status_);
  } else {
    status_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:clarifai.api.PostKnowledgeGraphMatchResponse)
}

void PostKnowledgeGraphMatchResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PostKnowledgeGraphMatchResponse_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  status_ = nullptr;
}

PostKnowledgeGraphMatchResponse::~PostKnowledgeGraphMatchResponse() {
  // @@protoc_insertion_point(destructor:clarifai.api.PostKnowledgeGraphMatchResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PostKnowledgeGraphMatchResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete status_;
}

void PostKnowledgeGraphMatchResponse::ArenaDtor(void* object) {
  PostKnowledgeGraphMatchResponse* _this = reinterpret_cast< PostKnowledgeGraphMatchResponse* >(object);
  (void)_this;
}
void PostKnowledgeGraphMatchResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PostKnowledgeGraphMatchResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PostKnowledgeGraphMatchResponse& PostKnowledgeGraphMatchResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PostKnowledgeGraphMatchResponse_proto_2fknowledge_5fgraph_2fkg_5fpy_5fservice_2eproto.base);
  return *internal_default_instance();
}


void PostKnowledgeGraphMatchResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.PostKnowledgeGraphMatchResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  concept_map_.Clear();
  if (GetArena() == nullptr && status_ != nullptr) {
    delete status_;
  }
  status_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PostKnowledgeGraphMatchResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .ResponseStatus status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_status(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .clarifai.api.ConceptMap concept_map = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_concept_map(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PostKnowledgeGraphMatchResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.PostKnowledgeGraphMatchResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ResponseStatus status = 1;
  if (this->has_status()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::status(this), target, stream);
  }

  // repeated .clarifai.api.ConceptMap concept_map = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_concept_map_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_concept_map(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.PostKnowledgeGraphMatchResponse)
  return target;
}

size_t PostKnowledgeGraphMatchResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.PostKnowledgeGraphMatchResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .clarifai.api.ConceptMap concept_map = 2;
  total_size += 1UL * this->_internal_concept_map_size();
  for (const auto& msg : this->concept_map_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .ResponseStatus status = 1;
  if (this->has_status()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *status_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PostKnowledgeGraphMatchResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:clarifai.api.PostKnowledgeGraphMatchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const PostKnowledgeGraphMatchResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PostKnowledgeGraphMatchResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:clarifai.api.PostKnowledgeGraphMatchResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:clarifai.api.PostKnowledgeGraphMatchResponse)
    MergeFrom(*source);
  }
}

void PostKnowledgeGraphMatchResponse::MergeFrom(const PostKnowledgeGraphMatchResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.PostKnowledgeGraphMatchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  concept_map_.MergeFrom(from.concept_map_);
  if (from.has_status()) {
    _internal_mutable_status()->::ResponseStatus::MergeFrom(from._internal_status());
  }
}

void PostKnowledgeGraphMatchResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:clarifai.api.PostKnowledgeGraphMatchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PostKnowledgeGraphMatchResponse::CopyFrom(const PostKnowledgeGraphMatchResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.PostKnowledgeGraphMatchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PostKnowledgeGraphMatchResponse::IsInitialized() const {
  return true;
}

void PostKnowledgeGraphMatchResponse::InternalSwap(PostKnowledgeGraphMatchResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  concept_map_.InternalSwap(&other->concept_map_);
  swap(status_, other->status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PostKnowledgeGraphMatchResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace clarifai
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::clarifai::api::ConceptMap* Arena::CreateMaybeMessage< ::clarifai::api::ConceptMap >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::ConceptMap >(arena);
}
template<> PROTOBUF_NOINLINE ::clarifai::api::ConceptEmbeddingDump* Arena::CreateMaybeMessage< ::clarifai::api::ConceptEmbeddingDump >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::ConceptEmbeddingDump >(arena);
}
template<> PROTOBUF_NOINLINE ::clarifai::api::CustomerDataDump* Arena::CreateMaybeMessage< ::clarifai::api::CustomerDataDump >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::CustomerDataDump >(arena);
}
template<> PROTOBUF_NOINLINE ::clarifai::api::PostKnowledgeGraphMatchRequest* Arena::CreateMaybeMessage< ::clarifai::api::PostKnowledgeGraphMatchRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::PostKnowledgeGraphMatchRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::clarifai::api::PostKnowledgeGraphMatchResponse* Arena::CreateMaybeMessage< ::clarifai::api::PostKnowledgeGraphMatchResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::PostKnowledgeGraphMatchResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
