// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/utils/face.proto

#include "proto/utils/face.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_proto_2futils_2fboundingbox_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_BoundingBox_proto_2futils_2fboundingbox_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2futils_2fembedding_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Embedding_proto_2futils_2fembedding_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2futils_2fface_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Face_proto_2futils_2fface_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_proto_2futils_2ftag_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Tag_proto_2futils_2ftag_2eproto;
class FaceDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Face> _instance;
} _Face_default_instance_;
class FaceDetectionDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FaceDetection> _instance;
} _FaceDetection_default_instance_;
static void InitDefaultsscc_info_Face_proto_2futils_2fface_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Face_default_instance_;
    new (ptr) ::Face();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Face::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Face_proto_2futils_2fface_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_Face_proto_2futils_2fface_2eproto}, {
      &scc_info_Tag_proto_2futils_2ftag_2eproto.base,}};

static void InitDefaultsscc_info_FaceDetection_proto_2futils_2fface_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_FaceDetection_default_instance_;
    new (ptr) ::FaceDetection();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::FaceDetection::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_FaceDetection_proto_2futils_2fface_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_FaceDetection_proto_2futils_2fface_2eproto}, {
      &scc_info_BoundingBox_proto_2futils_2fboundingbox_2eproto.base,
      &scc_info_Face_proto_2futils_2fface_2eproto.base,
      &scc_info_Embedding_proto_2futils_2fembedding_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2futils_2fface_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2futils_2fface_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2futils_2fface_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2futils_2fface_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Face, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Face, identity_),
  PROTOBUF_FIELD_OFFSET(::Face, age_),
  PROTOBUF_FIELD_OFFSET(::Face, gender_),
  PROTOBUF_FIELD_OFFSET(::Face, ethnicity_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::FaceDetection, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::FaceDetection, box_),
  PROTOBUF_FIELD_OFFSET(::FaceDetection, face_),
  PROTOBUF_FIELD_OFFSET(::FaceDetection, embedding_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Face)},
  { 9, -1, sizeof(::FaceDetection)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_Face_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_FaceDetection_default_instance_),
};

const char descriptor_table_protodef_proto_2futils_2fface_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026proto/utils/face.proto\032\025proto/utils/ta"
  "g.proto\032\035proto/utils/boundingbox.proto\032\033"
  "proto/utils/embedding.proto\"`\n\004Face\022\026\n\010i"
  "dentity\030\001 \003(\0132\004.Tag\022\021\n\003age\030\002 \003(\0132\004.Tag\022\024"
  "\n\006gender\030\003 \003(\0132\004.Tag\022\027\n\tethnicity\030\004 \003(\0132"
  "\004.Tag\"^\n\rFaceDetection\022\031\n\003box\030\001 \001(\0132\014.Bo"
  "undingBox\022\023\n\004face\030\002 \001(\0132\005.Face\022\035\n\tembedd"
  "ing\030\003 \001(\0132\n.EmbeddingB\016\n\005utilsZ\005utilsb\006p"
  "roto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2futils_2fface_2eproto_deps[3] = {
  &::descriptor_table_proto_2futils_2fboundingbox_2eproto,
  &::descriptor_table_proto_2futils_2fembedding_2eproto,
  &::descriptor_table_proto_2futils_2ftag_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2futils_2fface_2eproto_sccs[2] = {
  &scc_info_Face_proto_2futils_2fface_2eproto.base,
  &scc_info_FaceDetection_proto_2futils_2fface_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2futils_2fface_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2futils_2fface_2eproto = {
  false, false, descriptor_table_protodef_proto_2futils_2fface_2eproto, "proto/utils/face.proto", 325,
  &descriptor_table_proto_2futils_2fface_2eproto_once, descriptor_table_proto_2futils_2fface_2eproto_sccs, descriptor_table_proto_2futils_2fface_2eproto_deps, 2, 3,
  schemas, file_default_instances, TableStruct_proto_2futils_2fface_2eproto::offsets,
  file_level_metadata_proto_2futils_2fface_2eproto, 2, file_level_enum_descriptors_proto_2futils_2fface_2eproto, file_level_service_descriptors_proto_2futils_2fface_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2futils_2fface_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2futils_2fface_2eproto)), true);

// ===================================================================

void Face::InitAsDefaultInstance() {
}
class Face::_Internal {
 public:
};

void Face::clear_identity() {
  identity_.Clear();
}
void Face::clear_age() {
  age_.Clear();
}
void Face::clear_gender() {
  gender_.Clear();
}
void Face::clear_ethnicity() {
  ethnicity_.Clear();
}
Face::Face(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  identity_(arena),
  age_(arena),
  gender_(arena),
  ethnicity_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Face)
}
Face::Face(const Face& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      identity_(from.identity_),
      age_(from.age_),
      gender_(from.gender_),
      ethnicity_(from.ethnicity_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Face)
}

void Face::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Face_proto_2futils_2fface_2eproto.base);
}

Face::~Face() {
  // @@protoc_insertion_point(destructor:Face)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Face::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Face::ArenaDtor(void* object) {
  Face* _this = reinterpret_cast< Face* >(object);
  (void)_this;
}
void Face::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Face::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Face& Face::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Face_proto_2futils_2fface_2eproto.base);
  return *internal_default_instance();
}


void Face::Clear() {
// @@protoc_insertion_point(message_clear_start:Face)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  identity_.Clear();
  age_.Clear();
  gender_.Clear();
  ethnicity_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Face::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .Tag identity = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_identity(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .Tag age = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_age(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .Tag gender = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_gender(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .Tag ethnicity = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ethnicity(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Face::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Face)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Tag identity = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_identity_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_identity(i), target, stream);
  }

  // repeated .Tag age = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_age_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_age(i), target, stream);
  }

  // repeated .Tag gender = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_gender_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_gender(i), target, stream);
  }

  // repeated .Tag ethnicity = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_ethnicity_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_ethnicity(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Face)
  return target;
}

size_t Face::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Face)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Tag identity = 1;
  total_size += 1UL * this->_internal_identity_size();
  for (const auto& msg : this->identity_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Tag age = 2;
  total_size += 1UL * this->_internal_age_size();
  for (const auto& msg : this->age_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Tag gender = 3;
  total_size += 1UL * this->_internal_gender_size();
  for (const auto& msg : this->gender_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Tag ethnicity = 4;
  total_size += 1UL * this->_internal_ethnicity_size();
  for (const auto& msg : this->ethnicity_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Face::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Face)
  GOOGLE_DCHECK_NE(&from, this);
  const Face* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Face>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Face)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Face)
    MergeFrom(*source);
  }
}

void Face::MergeFrom(const Face& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Face)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  identity_.MergeFrom(from.identity_);
  age_.MergeFrom(from.age_);
  gender_.MergeFrom(from.gender_);
  ethnicity_.MergeFrom(from.ethnicity_);
}

void Face::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Face)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Face::CopyFrom(const Face& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Face)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Face::IsInitialized() const {
  return true;
}

void Face::InternalSwap(Face* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  identity_.InternalSwap(&other->identity_);
  age_.InternalSwap(&other->age_);
  gender_.InternalSwap(&other->gender_);
  ethnicity_.InternalSwap(&other->ethnicity_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Face::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void FaceDetection::InitAsDefaultInstance() {
  ::_FaceDetection_default_instance_._instance.get_mutable()->box_ = const_cast< ::BoundingBox*>(
      ::BoundingBox::internal_default_instance());
  ::_FaceDetection_default_instance_._instance.get_mutable()->face_ = const_cast< ::Face*>(
      ::Face::internal_default_instance());
  ::_FaceDetection_default_instance_._instance.get_mutable()->embedding_ = const_cast< ::Embedding*>(
      ::Embedding::internal_default_instance());
}
class FaceDetection::_Internal {
 public:
  static const ::BoundingBox& box(const FaceDetection* msg);
  static const ::Face& face(const FaceDetection* msg);
  static const ::Embedding& embedding(const FaceDetection* msg);
};

const ::BoundingBox&
FaceDetection::_Internal::box(const FaceDetection* msg) {
  return *msg->box_;
}
const ::Face&
FaceDetection::_Internal::face(const FaceDetection* msg) {
  return *msg->face_;
}
const ::Embedding&
FaceDetection::_Internal::embedding(const FaceDetection* msg) {
  return *msg->embedding_;
}
void FaceDetection::clear_box() {
  if (GetArena() == nullptr && box_ != nullptr) {
    delete box_;
  }
  box_ = nullptr;
}
void FaceDetection::clear_embedding() {
  if (GetArena() == nullptr && embedding_ != nullptr) {
    delete embedding_;
  }
  embedding_ = nullptr;
}
FaceDetection::FaceDetection(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:FaceDetection)
}
FaceDetection::FaceDetection(const FaceDetection& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_box()) {
    box_ = new ::BoundingBox(*from.box_);
  } else {
    box_ = nullptr;
  }
  if (from._internal_has_face()) {
    face_ = new ::Face(*from.face_);
  } else {
    face_ = nullptr;
  }
  if (from._internal_has_embedding()) {
    embedding_ = new ::Embedding(*from.embedding_);
  } else {
    embedding_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:FaceDetection)
}

void FaceDetection::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FaceDetection_proto_2futils_2fface_2eproto.base);
  ::memset(&box_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&embedding_) -
      reinterpret_cast<char*>(&box_)) + sizeof(embedding_));
}

FaceDetection::~FaceDetection() {
  // @@protoc_insertion_point(destructor:FaceDetection)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FaceDetection::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete box_;
  if (this != internal_default_instance()) delete face_;
  if (this != internal_default_instance()) delete embedding_;
}

void FaceDetection::ArenaDtor(void* object) {
  FaceDetection* _this = reinterpret_cast< FaceDetection* >(object);
  (void)_this;
}
void FaceDetection::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FaceDetection::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FaceDetection& FaceDetection::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FaceDetection_proto_2futils_2fface_2eproto.base);
  return *internal_default_instance();
}


void FaceDetection::Clear() {
// @@protoc_insertion_point(message_clear_start:FaceDetection)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && box_ != nullptr) {
    delete box_;
  }
  box_ = nullptr;
  if (GetArena() == nullptr && face_ != nullptr) {
    delete face_;
  }
  face_ = nullptr;
  if (GetArena() == nullptr && embedding_ != nullptr) {
    delete embedding_;
  }
  embedding_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FaceDetection::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .BoundingBox box = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_box(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .Face face = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_face(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .Embedding embedding = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_embedding(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FaceDetection::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FaceDetection)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .BoundingBox box = 1;
  if (this->has_box()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::box(this), target, stream);
  }

  // .Face face = 2;
  if (this->has_face()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::face(this), target, stream);
  }

  // .Embedding embedding = 3;
  if (this->has_embedding()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::embedding(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FaceDetection)
  return target;
}

size_t FaceDetection::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FaceDetection)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .BoundingBox box = 1;
  if (this->has_box()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *box_);
  }

  // .Face face = 2;
  if (this->has_face()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *face_);
  }

  // .Embedding embedding = 3;
  if (this->has_embedding()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *embedding_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FaceDetection::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FaceDetection)
  GOOGLE_DCHECK_NE(&from, this);
  const FaceDetection* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FaceDetection>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FaceDetection)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FaceDetection)
    MergeFrom(*source);
  }
}

void FaceDetection::MergeFrom(const FaceDetection& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FaceDetection)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_box()) {
    _internal_mutable_box()->::BoundingBox::MergeFrom(from._internal_box());
  }
  if (from.has_face()) {
    _internal_mutable_face()->::Face::MergeFrom(from._internal_face());
  }
  if (from.has_embedding()) {
    _internal_mutable_embedding()->::Embedding::MergeFrom(from._internal_embedding());
  }
}

void FaceDetection::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FaceDetection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FaceDetection::CopyFrom(const FaceDetection& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FaceDetection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FaceDetection::IsInitialized() const {
  return true;
}

void FaceDetection::InternalSwap(FaceDetection* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FaceDetection, embedding_)
      + sizeof(FaceDetection::embedding_)
      - PROTOBUF_FIELD_OFFSET(FaceDetection, box_)>(
          reinterpret_cast<char*>(&box_),
          reinterpret_cast<char*>(&other->box_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FaceDetection::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Face* Arena::CreateMaybeMessage< ::Face >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Face >(arena);
}
template<> PROTOBUF_NOINLINE ::FaceDetection* Arena::CreateMaybeMessage< ::FaceDetection >(Arena* arena) {
  return Arena::CreateMessageInternal< ::FaceDetection >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
