# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/utils/lopq_code.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.clarifai.api.utils import extensions_pb2 as proto_dot_clarifai_dot_api_dot_utils_dot_extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/utils/lopq_code.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\005utilsZ\005utils',
  serialized_pb=b'\n\x1bproto/utils/lopq_code.proto\x1a)proto/clarifai/api/utils/extensions.proto\"J\n\x08LOPQCode\x12\x12\n\ncoarse_key\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ine_key\x18\x02 \x01(\x0c\x12\x18\n\nprojection\x18\x03 \x03(\x02\x42\x04\x80\xb5\x18\x01\x42\x0e\n\x05utilsZ\x05utilsb\x06proto3'
  ,
  dependencies=[proto_dot_clarifai_dot_api_dot_utils_dot_extensions__pb2.DESCRIPTOR,])




_LOPQCODE = _descriptor.Descriptor(
  name='LOPQCode',
  full_name='LOPQCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coarse_key', full_name='LOPQCode.coarse_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fine_key', full_name='LOPQCode.fine_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projection', full_name='LOPQCode.projection', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\200\265\030\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['LOPQCode'] = _LOPQCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LOPQCode = _reflection.GeneratedProtocolMessageType('LOPQCode', (_message.Message,), {
  'DESCRIPTOR' : _LOPQCODE,
  '__module__' : 'proto.utils.lopq_code_pb2'
  # @@protoc_insertion_point(class_scope:LOPQCode)
  })
_sym_db.RegisterMessage(LOPQCode)


DESCRIPTOR._options = None
_LOPQCODE.fields_by_name['projection']._options = None
# @@protoc_insertion_point(module_scope)
