// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/utils/request_meta.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2futils_2frequest_5fmeta_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2futils_2frequest_5fmeta_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/duration.pb.h>
#include "proto/clarifai/api/status/status_code.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2futils_2frequest_5fmeta_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2futils_2frequest_5fmeta_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2futils_2frequest_5fmeta_2eproto;
class RequestMeta;
class RequestMetaDefaultTypeInternal;
extern RequestMetaDefaultTypeInternal _RequestMeta_default_instance_;
class RequestMeta_MetadataEntry_DoNotUse;
class RequestMeta_MetadataEntry_DoNotUseDefaultTypeInternal;
extern RequestMeta_MetadataEntry_DoNotUseDefaultTypeInternal _RequestMeta_MetadataEntry_DoNotUse_default_instance_;
class ResponseStatus;
class ResponseStatusDefaultTypeInternal;
extern ResponseStatusDefaultTypeInternal _ResponseStatus_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::RequestMeta* Arena::CreateMaybeMessage<::RequestMeta>(Arena*);
template<> ::RequestMeta_MetadataEntry_DoNotUse* Arena::CreateMaybeMessage<::RequestMeta_MetadataEntry_DoNotUse>(Arena*);
template<> ::ResponseStatus* Arena::CreateMaybeMessage<::ResponseStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ResponseStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ResponseStatus) */ {
 public:
  inline ResponseStatus() : ResponseStatus(nullptr) {}
  virtual ~ResponseStatus();

  ResponseStatus(const ResponseStatus& from);
  ResponseStatus(ResponseStatus&& from) noexcept
    : ResponseStatus() {
    *this = ::std::move(from);
  }

  inline ResponseStatus& operator=(const ResponseStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResponseStatus& operator=(ResponseStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResponseStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponseStatus* internal_default_instance() {
    return reinterpret_cast<const ResponseStatus*>(
               &_ResponseStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResponseStatus& a, ResponseStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(ResponseStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResponseStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResponseStatus* New() const final {
    return CreateMaybeMessage<ResponseStatus>(nullptr);
  }

  ResponseStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResponseStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResponseStatus& from);
  void MergeFrom(const ResponseStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponseStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ResponseStatus";
  }
  protected:
  explicit ResponseStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2futils_2frequest_5fmeta_2eproto);
    return ::descriptor_table_proto_2futils_2frequest_5fmeta_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserMsgFieldNumber = 3,
    kExceptionMsgFieldNumber = 4,
    kTraceFieldNumber = 5,
    kDurationFieldNumber = 1003,
    kOkFieldNumber = 1,
    kCodeFieldNumber = 2,
  };
  // string user_msg = 3;
  void clear_user_msg();
  const std::string& user_msg() const;
  void set_user_msg(const std::string& value);
  void set_user_msg(std::string&& value);
  void set_user_msg(const char* value);
  void set_user_msg(const char* value, size_t size);
  std::string* mutable_user_msg();
  std::string* release_user_msg();
  void set_allocated_user_msg(std::string* user_msg);
  private:
  const std::string& _internal_user_msg() const;
  void _internal_set_user_msg(const std::string& value);
  std::string* _internal_mutable_user_msg();
  public:

  // string exception_msg = 4;
  void clear_exception_msg();
  const std::string& exception_msg() const;
  void set_exception_msg(const std::string& value);
  void set_exception_msg(std::string&& value);
  void set_exception_msg(const char* value);
  void set_exception_msg(const char* value, size_t size);
  std::string* mutable_exception_msg();
  std::string* release_exception_msg();
  void set_allocated_exception_msg(std::string* exception_msg);
  private:
  const std::string& _internal_exception_msg() const;
  void _internal_set_exception_msg(const std::string& value);
  std::string* _internal_mutable_exception_msg();
  public:

  // string trace = 5;
  void clear_trace();
  const std::string& trace() const;
  void set_trace(const std::string& value);
  void set_trace(std::string&& value);
  void set_trace(const char* value);
  void set_trace(const char* value, size_t size);
  std::string* mutable_trace();
  std::string* release_trace();
  void set_allocated_trace(std::string* trace);
  private:
  const std::string& _internal_trace() const;
  void _internal_set_trace(const std::string& value);
  std::string* _internal_mutable_trace();
  public:

  // .google.protobuf.Duration duration = 1003;
  bool has_duration() const;
  private:
  bool _internal_has_duration() const;
  public:
  void clear_duration();
  const PROTOBUF_NAMESPACE_ID::Duration& duration() const;
  PROTOBUF_NAMESPACE_ID::Duration* release_duration();
  PROTOBUF_NAMESPACE_ID::Duration* mutable_duration();
  void set_allocated_duration(PROTOBUF_NAMESPACE_ID::Duration* duration);
  private:
  const PROTOBUF_NAMESPACE_ID::Duration& _internal_duration() const;
  PROTOBUF_NAMESPACE_ID::Duration* _internal_mutable_duration();
  public:
  void unsafe_arena_set_allocated_duration(
      PROTOBUF_NAMESPACE_ID::Duration* duration);
  PROTOBUF_NAMESPACE_ID::Duration* unsafe_arena_release_duration();

  // bool ok = 1;
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // .clarifai.api.status.StatusCode code = 2;
  void clear_code();
  ::clarifai::api::status::StatusCode code() const;
  void set_code(::clarifai::api::status::StatusCode value);
  private:
  ::clarifai::api::status::StatusCode _internal_code() const;
  void _internal_set_code(::clarifai::api::status::StatusCode value);
  public:

  // @@protoc_insertion_point(class_scope:ResponseStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_msg_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr exception_msg_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trace_;
  PROTOBUF_NAMESPACE_ID::Duration* duration_;
  bool ok_;
  int code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2futils_2frequest_5fmeta_2eproto;
};
// -------------------------------------------------------------------

class RequestMeta_MetadataEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<RequestMeta_MetadataEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<RequestMeta_MetadataEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  RequestMeta_MetadataEntry_DoNotUse();
  explicit RequestMeta_MetadataEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const RequestMeta_MetadataEntry_DoNotUse& other);
  static const RequestMeta_MetadataEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const RequestMeta_MetadataEntry_DoNotUse*>(&_RequestMeta_MetadataEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "RequestMeta.MetadataEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "RequestMeta.MetadataEntry.value");
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2futils_2frequest_5fmeta_2eproto);
    return ::descriptor_table_proto_2futils_2frequest_5fmeta_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class RequestMeta PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RequestMeta) */ {
 public:
  inline RequestMeta() : RequestMeta(nullptr) {}
  virtual ~RequestMeta();

  RequestMeta(const RequestMeta& from);
  RequestMeta(RequestMeta&& from) noexcept
    : RequestMeta() {
    *this = ::std::move(from);
  }

  inline RequestMeta& operator=(const RequestMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestMeta& operator=(RequestMeta&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RequestMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestMeta* internal_default_instance() {
    return reinterpret_cast<const RequestMeta*>(
               &_RequestMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RequestMeta& a, RequestMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestMeta* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RequestMeta* New() const final {
    return CreateMaybeMessage<RequestMeta>(nullptr);
  }

  RequestMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RequestMeta>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RequestMeta& from);
  void MergeFrom(const RequestMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestMeta* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RequestMeta";
  }
  protected:
  explicit RequestMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2futils_2frequest_5fmeta_2eproto);
    return ::descriptor_table_proto_2futils_2frequest_5fmeta_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kMetadataFieldNumber = 2,
    kRequestIDFieldNumber = 1,
    kRequesterIDFieldNumber = 3,
  };
  // map<string, string> metadata = 2;
  int metadata_size() const;
  private:
  int _internal_metadata_size() const;
  public:
  void clear_metadata();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_metadata() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_metadata();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      metadata() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_metadata();

  // string requestID = 1;
  void clear_requestid();
  const std::string& requestid() const;
  void set_requestid(const std::string& value);
  void set_requestid(std::string&& value);
  void set_requestid(const char* value);
  void set_requestid(const char* value, size_t size);
  std::string* mutable_requestid();
  std::string* release_requestid();
  void set_allocated_requestid(std::string* requestid);
  private:
  const std::string& _internal_requestid() const;
  void _internal_set_requestid(const std::string& value);
  std::string* _internal_mutable_requestid();
  public:

  // string requesterID = 3;
  void clear_requesterid();
  const std::string& requesterid() const;
  void set_requesterid(const std::string& value);
  void set_requesterid(std::string&& value);
  void set_requesterid(const char* value);
  void set_requesterid(const char* value, size_t size);
  std::string* mutable_requesterid();
  std::string* release_requesterid();
  void set_allocated_requesterid(std::string* requesterid);
  private:
  const std::string& _internal_requesterid() const;
  void _internal_set_requesterid(const std::string& value);
  std::string* _internal_mutable_requesterid();
  public:

  // @@protoc_insertion_point(class_scope:RequestMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      RequestMeta_MetadataEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      0 > metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr requestid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr requesterid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2futils_2frequest_5fmeta_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResponseStatus

// bool ok = 1;
inline void ResponseStatus::clear_ok() {
  ok_ = false;
}
inline bool ResponseStatus::_internal_ok() const {
  return ok_;
}
inline bool ResponseStatus::ok() const {
  // @@protoc_insertion_point(field_get:ResponseStatus.ok)
  return _internal_ok();
}
inline void ResponseStatus::_internal_set_ok(bool value) {
  
  ok_ = value;
}
inline void ResponseStatus::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:ResponseStatus.ok)
}

// .clarifai.api.status.StatusCode code = 2;
inline void ResponseStatus::clear_code() {
  code_ = 0;
}
inline ::clarifai::api::status::StatusCode ResponseStatus::_internal_code() const {
  return static_cast< ::clarifai::api::status::StatusCode >(code_);
}
inline ::clarifai::api::status::StatusCode ResponseStatus::code() const {
  // @@protoc_insertion_point(field_get:ResponseStatus.code)
  return _internal_code();
}
inline void ResponseStatus::_internal_set_code(::clarifai::api::status::StatusCode value) {
  
  code_ = value;
}
inline void ResponseStatus::set_code(::clarifai::api::status::StatusCode value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:ResponseStatus.code)
}

// string user_msg = 3;
inline void ResponseStatus::clear_user_msg() {
  user_msg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ResponseStatus::user_msg() const {
  // @@protoc_insertion_point(field_get:ResponseStatus.user_msg)
  return _internal_user_msg();
}
inline void ResponseStatus::set_user_msg(const std::string& value) {
  _internal_set_user_msg(value);
  // @@protoc_insertion_point(field_set:ResponseStatus.user_msg)
}
inline std::string* ResponseStatus::mutable_user_msg() {
  // @@protoc_insertion_point(field_mutable:ResponseStatus.user_msg)
  return _internal_mutable_user_msg();
}
inline const std::string& ResponseStatus::_internal_user_msg() const {
  return user_msg_.Get();
}
inline void ResponseStatus::_internal_set_user_msg(const std::string& value) {
  
  user_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ResponseStatus::set_user_msg(std::string&& value) {
  
  user_msg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ResponseStatus.user_msg)
}
inline void ResponseStatus::set_user_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  user_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ResponseStatus.user_msg)
}
inline void ResponseStatus::set_user_msg(const char* value,
    size_t size) {
  
  user_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ResponseStatus.user_msg)
}
inline std::string* ResponseStatus::_internal_mutable_user_msg() {
  
  return user_msg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ResponseStatus::release_user_msg() {
  // @@protoc_insertion_point(field_release:ResponseStatus.user_msg)
  return user_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ResponseStatus::set_allocated_user_msg(std::string* user_msg) {
  if (user_msg != nullptr) {
    
  } else {
    
  }
  user_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_msg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ResponseStatus.user_msg)
}

// string exception_msg = 4;
inline void ResponseStatus::clear_exception_msg() {
  exception_msg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ResponseStatus::exception_msg() const {
  // @@protoc_insertion_point(field_get:ResponseStatus.exception_msg)
  return _internal_exception_msg();
}
inline void ResponseStatus::set_exception_msg(const std::string& value) {
  _internal_set_exception_msg(value);
  // @@protoc_insertion_point(field_set:ResponseStatus.exception_msg)
}
inline std::string* ResponseStatus::mutable_exception_msg() {
  // @@protoc_insertion_point(field_mutable:ResponseStatus.exception_msg)
  return _internal_mutable_exception_msg();
}
inline const std::string& ResponseStatus::_internal_exception_msg() const {
  return exception_msg_.Get();
}
inline void ResponseStatus::_internal_set_exception_msg(const std::string& value) {
  
  exception_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ResponseStatus::set_exception_msg(std::string&& value) {
  
  exception_msg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ResponseStatus.exception_msg)
}
inline void ResponseStatus::set_exception_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  exception_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ResponseStatus.exception_msg)
}
inline void ResponseStatus::set_exception_msg(const char* value,
    size_t size) {
  
  exception_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ResponseStatus.exception_msg)
}
inline std::string* ResponseStatus::_internal_mutable_exception_msg() {
  
  return exception_msg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ResponseStatus::release_exception_msg() {
  // @@protoc_insertion_point(field_release:ResponseStatus.exception_msg)
  return exception_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ResponseStatus::set_allocated_exception_msg(std::string* exception_msg) {
  if (exception_msg != nullptr) {
    
  } else {
    
  }
  exception_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), exception_msg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ResponseStatus.exception_msg)
}

// string trace = 5;
inline void ResponseStatus::clear_trace() {
  trace_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ResponseStatus::trace() const {
  // @@protoc_insertion_point(field_get:ResponseStatus.trace)
  return _internal_trace();
}
inline void ResponseStatus::set_trace(const std::string& value) {
  _internal_set_trace(value);
  // @@protoc_insertion_point(field_set:ResponseStatus.trace)
}
inline std::string* ResponseStatus::mutable_trace() {
  // @@protoc_insertion_point(field_mutable:ResponseStatus.trace)
  return _internal_mutable_trace();
}
inline const std::string& ResponseStatus::_internal_trace() const {
  return trace_.Get();
}
inline void ResponseStatus::_internal_set_trace(const std::string& value) {
  
  trace_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ResponseStatus::set_trace(std::string&& value) {
  
  trace_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ResponseStatus.trace)
}
inline void ResponseStatus::set_trace(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trace_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ResponseStatus.trace)
}
inline void ResponseStatus::set_trace(const char* value,
    size_t size) {
  
  trace_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ResponseStatus.trace)
}
inline std::string* ResponseStatus::_internal_mutable_trace() {
  
  return trace_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ResponseStatus::release_trace() {
  // @@protoc_insertion_point(field_release:ResponseStatus.trace)
  return trace_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ResponseStatus::set_allocated_trace(std::string* trace) {
  if (trace != nullptr) {
    
  } else {
    
  }
  trace_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trace,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ResponseStatus.trace)
}

// .google.protobuf.Duration duration = 1003;
inline bool ResponseStatus::_internal_has_duration() const {
  return this != internal_default_instance() && duration_ != nullptr;
}
inline bool ResponseStatus::has_duration() const {
  return _internal_has_duration();
}
inline const PROTOBUF_NAMESPACE_ID::Duration& ResponseStatus::_internal_duration() const {
  const PROTOBUF_NAMESPACE_ID::Duration* p = duration_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Duration*>(
      &PROTOBUF_NAMESPACE_ID::_Duration_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Duration& ResponseStatus::duration() const {
  // @@protoc_insertion_point(field_get:ResponseStatus.duration)
  return _internal_duration();
}
inline void ResponseStatus::unsafe_arena_set_allocated_duration(
    PROTOBUF_NAMESPACE_ID::Duration* duration) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(duration_);
  }
  duration_ = duration;
  if (duration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ResponseStatus.duration)
}
inline PROTOBUF_NAMESPACE_ID::Duration* ResponseStatus::release_duration() {
  
  PROTOBUF_NAMESPACE_ID::Duration* temp = duration_;
  duration_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Duration* ResponseStatus::unsafe_arena_release_duration() {
  // @@protoc_insertion_point(field_release:ResponseStatus.duration)
  
  PROTOBUF_NAMESPACE_ID::Duration* temp = duration_;
  duration_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Duration* ResponseStatus::_internal_mutable_duration() {
  
  if (duration_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Duration>(GetArena());
    duration_ = p;
  }
  return duration_;
}
inline PROTOBUF_NAMESPACE_ID::Duration* ResponseStatus::mutable_duration() {
  // @@protoc_insertion_point(field_mutable:ResponseStatus.duration)
  return _internal_mutable_duration();
}
inline void ResponseStatus::set_allocated_duration(PROTOBUF_NAMESPACE_ID::Duration* duration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(duration_);
  }
  if (duration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(duration)->GetArena();
    if (message_arena != submessage_arena) {
      duration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, duration, submessage_arena);
    }
    
  } else {
    
  }
  duration_ = duration;
  // @@protoc_insertion_point(field_set_allocated:ResponseStatus.duration)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RequestMeta

// string requestID = 1;
inline void RequestMeta::clear_requestid() {
  requestid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RequestMeta::requestid() const {
  // @@protoc_insertion_point(field_get:RequestMeta.requestID)
  return _internal_requestid();
}
inline void RequestMeta::set_requestid(const std::string& value) {
  _internal_set_requestid(value);
  // @@protoc_insertion_point(field_set:RequestMeta.requestID)
}
inline std::string* RequestMeta::mutable_requestid() {
  // @@protoc_insertion_point(field_mutable:RequestMeta.requestID)
  return _internal_mutable_requestid();
}
inline const std::string& RequestMeta::_internal_requestid() const {
  return requestid_.Get();
}
inline void RequestMeta::_internal_set_requestid(const std::string& value) {
  
  requestid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RequestMeta::set_requestid(std::string&& value) {
  
  requestid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:RequestMeta.requestID)
}
inline void RequestMeta::set_requestid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  requestid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:RequestMeta.requestID)
}
inline void RequestMeta::set_requestid(const char* value,
    size_t size) {
  
  requestid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:RequestMeta.requestID)
}
inline std::string* RequestMeta::_internal_mutable_requestid() {
  
  return requestid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RequestMeta::release_requestid() {
  // @@protoc_insertion_point(field_release:RequestMeta.requestID)
  return requestid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RequestMeta::set_allocated_requestid(std::string* requestid) {
  if (requestid != nullptr) {
    
  } else {
    
  }
  requestid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), requestid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:RequestMeta.requestID)
}

// map<string, string> metadata = 2;
inline int RequestMeta::_internal_metadata_size() const {
  return metadata_.size();
}
inline int RequestMeta::metadata_size() const {
  return _internal_metadata_size();
}
inline void RequestMeta::clear_metadata() {
  metadata_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
RequestMeta::_internal_metadata() const {
  return metadata_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
RequestMeta::metadata() const {
  // @@protoc_insertion_point(field_map:RequestMeta.metadata)
  return _internal_metadata();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
RequestMeta::_internal_mutable_metadata() {
  return metadata_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
RequestMeta::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_map:RequestMeta.metadata)
  return _internal_mutable_metadata();
}

// string requesterID = 3;
inline void RequestMeta::clear_requesterid() {
  requesterid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RequestMeta::requesterid() const {
  // @@protoc_insertion_point(field_get:RequestMeta.requesterID)
  return _internal_requesterid();
}
inline void RequestMeta::set_requesterid(const std::string& value) {
  _internal_set_requesterid(value);
  // @@protoc_insertion_point(field_set:RequestMeta.requesterID)
}
inline std::string* RequestMeta::mutable_requesterid() {
  // @@protoc_insertion_point(field_mutable:RequestMeta.requesterID)
  return _internal_mutable_requesterid();
}
inline const std::string& RequestMeta::_internal_requesterid() const {
  return requesterid_.Get();
}
inline void RequestMeta::_internal_set_requesterid(const std::string& value) {
  
  requesterid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RequestMeta::set_requesterid(std::string&& value) {
  
  requesterid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:RequestMeta.requesterID)
}
inline void RequestMeta::set_requesterid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  requesterid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:RequestMeta.requesterID)
}
inline void RequestMeta::set_requesterid(const char* value,
    size_t size) {
  
  requesterid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:RequestMeta.requesterID)
}
inline std::string* RequestMeta::_internal_mutable_requesterid() {
  
  return requesterid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RequestMeta::release_requesterid() {
  // @@protoc_insertion_point(field_release:RequestMeta.requesterID)
  return requesterid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RequestMeta::set_allocated_requesterid(std::string* requesterid) {
  if (requesterid != nullptr) {
    
  } else {
    
  }
  requesterid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), requesterid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:RequestMeta.requesterID)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2futils_2frequest_5fmeta_2eproto
